"""Add ServiceLocationOffset table

Revision ID: 62b1aa69eb4d
Revises: 
Create Date: 2024-10-13 19:58:09.865375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1aa69eb4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('is_offset_time')
        batch_op.drop_column('offset_time_up')
        batch_op.drop_column('offset_time_down')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('is_offset_time')
        batch_op.drop_column('offset_time_up')
        batch_op.drop_column('offset_time_down')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset_time_down', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('offset_time_up', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('is_offset_time', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset_time_down', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('offset_time_up', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('is_offset_time', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
