"""add counter

Revision ID: 735b08b7d9c8
Revises: ea7406a65724
Create Date: 2026-02-23 17:30:48.436078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735b08b7d9c8'
down_revision = 'ea7406a65724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location_offset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location_offset', schema=None) as batch_op:
        batch_op.drop_column('counter')

    # ### end Alembic commands ###
