"""Add priority column to service_location table1

Revision ID: 7dd6929c50bc
Revises: 62b1aa69eb4d
Create Date: 2024-10-13 20:45:06.086530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd6929c50bc'
down_revision = '62b1aa69eb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
