"""empty message

Revision ID: e1704b42868a
Revises: 
Create Date: 2021-07-30 14:57:50.579713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1704b42868a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shot_name', sa.String(length=50), nullable=False),
    sa.Column('contacts', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Организации'
    )
    op.create_table('priority',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Приоритеты'
    )
    op.create_index(op.f('ix_public_priority_id'), 'priority', ['id'], unique=False, schema='public')
    op.create_table('service_zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Зоны обслуживания'
    )
    op.create_index(op.f('ix_public_service_zone_id'), 'service_zone', ['id'], unique=False, schema='public')
    op.create_table('template_sound_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='шаблон звукового сопровождения'
    )
    op.create_index(op.f('ix_public_template_sound_alert_id'), 'template_sound_alert', ['id'], unique=False, schema='public')
    op.create_table('time_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Расписание'
    )
    op.create_index(op.f('ix_public_time_table_id'), 'time_table', ['id'], unique=False, schema='public')
    op.create_table('type_client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='тип клинета'
    )
    op.create_index(op.f('ix_public_type_client_id'), 'type_client', ['id'], unique=False, schema='public')
    op.create_table('type_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='тип новостей'
    )
    op.create_index(op.f('ix_public_type_news_id'), 'type_news', ['id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True, comment='Имя пользователя'),
    sa.Column('password', sa.String(length=120), nullable=False, comment='Пароль'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='Статус'),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='public',
    comment='Пользователи'
    )
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.Column('mac_address', sa.String(length=48), nullable=False, comment='Мак адрес'),
    sa.Column('service_zone', sa.Integer(), nullable=False, comment='Зона обслуживаня'),
    sa.ForeignKeyConstraint(['service_zone'], ['public.service_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Клинеты'
    )
    op.create_index(op.f('ix_public_clients_id'), 'clients', ['id'], unique=False, schema='public')
    op.create_table('information_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='наименование'),
    sa.Column('service_zone', sa.Integer(), nullable=False, comment='Зона обслуживаня'),
    sa.Column('view_list', sa.Boolean(), nullable=False, comment='список ожидающих'),
    sa.Column('news_event', sa.Integer(), nullable=False, comment='Тип новости(видео, картинка, бегущая строка)'),
    sa.Column('count_windows', sa.Integer(), nullable=False, comment='количество отображаемых окон'),
    sa.ForeignKeyConstraint(['news_event'], ['public.type_news.id'], ),
    sa.ForeignKeyConstraint(['service_zone'], ['public.service_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Информационное табло'
    )
    op.create_index(op.f('ix_public_information_table_id'), 'information_table', ['id'], unique=False, schema='public')
    op.create_table('news_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_news', sa.Integer(), nullable=False, comment='Тип новости(видео, картинка, бегущая строка)'),
    sa.Column('head', sa.String(length=100), nullable=False),
    sa.Column('service_zone', sa.Integer(), nullable=False, comment='Зона обслуживаня'),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['service_zone'], ['public.service_zone.id'], ),
    sa.ForeignKeyConstraint(['type_news'], ['public.type_news.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='новости, реклама'
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('prefix', sa.CHAR(length=1), nullable=False),
    sa.Column('start_num', sa.Integer(), nullable=False),
    sa.Column('timetable', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False, comment='Лимит талонов в день'),
    sa.Column('view_display', sa.Boolean(), nullable=False, comment='Статус отображения на табло'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Статус'),
    sa.Column('template_sound_alert', sa.Integer(), nullable=False, comment='шаблон звукового сопровождения'),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['template_sound_alert'], ['public.template_sound_alert.id'], ),
    sa.ForeignKeyConstraint(['timetable'], ['public.time_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Улсуги'
    )
    op.create_index(op.f('ix_public_services_id'), 'services', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_services_template_sound_alert'), 'services', ['template_sound_alert'], unique=False, schema='public')
    op.create_index(op.f('ix_public_services_timetable'), 'services', ['timetable'], unique=False, schema='public')
    op.create_table('time_week',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_table', sa.Integer(), nullable=False),
    sa.Column('day_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('stop_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['time_table'], ['public.time_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='Время работы'
    )
    op.create_index(op.f('ix_public_time_week_day_week'), 'time_week', ['day_week'], unique=False, schema='public')
    op.create_index(op.f('ix_public_time_week_id'), 'time_week', ['id'], unique=False, schema='public')
    op.create_table('client_services',
    sa.Column('clients', sa.Integer(), nullable=True, comment='Идентификатор клинета'),
    sa.Column('services', sa.Integer(), nullable=True, comment='Идентификатор услуги'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Идентификатор приоритета'),
    sa.ForeignKeyConstraint(['clients'], ['public.clients.id'], ),
    sa.ForeignKeyConstraint(['priority'], ['public.priority.id'], ),
    sa.ForeignKeyConstraint(['services'], ['public.services.id'], )
    )
    op.create_table('informationtable_services',
    sa.Column('information_table', sa.Integer(), nullable=True, comment='Идентификатор информационного табло'),
    sa.Column('services', sa.Integer(), nullable=True, comment='Идентификатор услуги'),
    sa.ForeignKeyConstraint(['information_table'], ['public.information_table.id'], ),
    sa.ForeignKeyConstraint(['services'], ['public.services.id'], )
    )
    op.create_table('servicezone_services',
    sa.Column('service_zone', sa.Integer(), nullable=True, comment='Идентификатор зона обслуживания'),
    sa.Column('services', sa.Integer(), nullable=True, comment='Идентификатор услуги'),
    sa.ForeignKeyConstraint(['service_zone'], ['public.service_zone.id'], ),
    sa.ForeignKeyConstraint(['services'], ['public.services.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicezone_services')
    op.drop_table('informationtable_services')
    op.drop_table('client_services')
    op.drop_index(op.f('ix_public_time_week_id'), table_name='time_week', schema='public')
    op.drop_index(op.f('ix_public_time_week_day_week'), table_name='time_week', schema='public')
    op.drop_table('time_week', schema='public')
    op.drop_index(op.f('ix_public_services_timetable'), table_name='services', schema='public')
    op.drop_index(op.f('ix_public_services_template_sound_alert'), table_name='services', schema='public')
    op.drop_index(op.f('ix_public_services_id'), table_name='services', schema='public')
    op.drop_table('services', schema='public')
    op.drop_table('news_event', schema='public')
    op.drop_index(op.f('ix_public_information_table_id'), table_name='information_table', schema='public')
    op.drop_table('information_table', schema='public')
    op.drop_index(op.f('ix_public_clients_id'), table_name='clients', schema='public')
    op.drop_table('clients', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_type_news_id'), table_name='type_news', schema='public')
    op.drop_table('type_news', schema='public')
    op.drop_index(op.f('ix_public_type_client_id'), table_name='type_client', schema='public')
    op.drop_table('type_client', schema='public')
    op.drop_index(op.f('ix_public_time_table_id'), table_name='time_table', schema='public')
    op.drop_table('time_table', schema='public')
    op.drop_index(op.f('ix_public_template_sound_alert_id'), table_name='template_sound_alert', schema='public')
    op.drop_table('template_sound_alert', schema='public')
    op.drop_index(op.f('ix_public_service_zone_id'), table_name='service_zone', schema='public')
    op.drop_table('service_zone', schema='public')
    op.drop_index(op.f('ix_public_priority_id'), table_name='priority', schema='public')
    op.drop_table('priority', schema='public')
    op.drop_table('organization', schema='public')
    # ### end Alembic commands ###
