"""move priority to ServiceLocationOffset

Revision ID: ea7406a65724
Revises: 7dd6929c50bc
Create Date: 2024-10-14 20:36:20.148178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7406a65724'
down_revision = '7dd6929c50bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('service_location_offset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_location_offset', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('service_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
